// Code generated by protoc-gen-go. DO NOT EDIT.
// source: epl/protobuf/query.proto

package protobuf // import "github.com/geo-grpc/api/golang/epl/protobuf"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SortDirection int32

const (
	SortDirection_NOT_SORTED SortDirection = 0
	SortDirection_DESCENDING SortDirection = 1
	SortDirection_ASCENDING  SortDirection = 2
)

var SortDirection_name = map[int32]string{
	0: "NOT_SORTED",
	1: "DESCENDING",
	2: "ASCENDING",
}
var SortDirection_value = map[string]int32{
	"NOT_SORTED": 0,
	"DESCENDING": 1,
	"ASCENDING":  2,
}

func (x SortDirection) String() string {
	return proto.EnumName(SortDirection_name, int32(x))
}
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_query_78a5b0bbc1bbffce, []int{0}
}

type FieldRelationship int32

const (
	FieldRelationship_UNKNOWN_FIELD_REL   FieldRelationship = 0
	FieldRelationship_FIELD_EQUALS        FieldRelationship = 2
	FieldRelationship_FIELD_NOT_EQUAL     FieldRelationship = 4
	FieldRelationship_FIELD_LESS_EQUAL    FieldRelationship = 8
	FieldRelationship_FIELD_GREATER_EQUAL FieldRelationship = 16
	FieldRelationship_FIELD_LESS          FieldRelationship = 32
	FieldRelationship_FIELD_GREATER       FieldRelationship = 64
	FieldRelationship_FIELD_RANGE         FieldRelationship = 128
	FieldRelationship_FIELD_NOT_RANGE     FieldRelationship = 256
)

var FieldRelationship_name = map[int32]string{
	0:   "UNKNOWN_FIELD_REL",
	2:   "FIELD_EQUALS",
	4:   "FIELD_NOT_EQUAL",
	8:   "FIELD_LESS_EQUAL",
	16:  "FIELD_GREATER_EQUAL",
	32:  "FIELD_LESS",
	64:  "FIELD_GREATER",
	128: "FIELD_RANGE",
	256: "FIELD_NOT_RANGE",
}
var FieldRelationship_value = map[string]int32{
	"UNKNOWN_FIELD_REL":   0,
	"FIELD_EQUALS":        2,
	"FIELD_NOT_EQUAL":     4,
	"FIELD_LESS_EQUAL":    8,
	"FIELD_GREATER_EQUAL": 16,
	"FIELD_LESS":          32,
	"FIELD_GREATER":       64,
	"FIELD_RANGE":         128,
	"FIELD_NOT_RANGE":     256,
}

func (x FieldRelationship) String() string {
	return proto.EnumName(FieldRelationship_name, int32(x))
}
func (FieldRelationship) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_query_78a5b0bbc1bbffce, []int{1}
}

type FloatField struct {
	Value                float32           `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	RelType              FieldRelationship `protobuf:"varint,2,opt,name=rel_type,json=relType,proto3,enum=epl.protobuf.FieldRelationship" json:"rel_type,omitempty"`
	RangeValue           float32           `protobuf:"fixed32,3,opt,name=range_value,json=rangeValue,proto3" json:"range_value,omitempty"`
	SortDirection        SortDirection     `protobuf:"varint,4,opt,name=sort_direction,json=sortDirection,proto3,enum=epl.protobuf.SortDirection" json:"sort_direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FloatField) Reset()         { *m = FloatField{} }
func (m *FloatField) String() string { return proto.CompactTextString(m) }
func (*FloatField) ProtoMessage()    {}
func (*FloatField) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_78a5b0bbc1bbffce, []int{0}
}
func (m *FloatField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FloatField.Unmarshal(m, b)
}
func (m *FloatField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FloatField.Marshal(b, m, deterministic)
}
func (dst *FloatField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FloatField.Merge(dst, src)
}
func (m *FloatField) XXX_Size() int {
	return xxx_messageInfo_FloatField.Size(m)
}
func (m *FloatField) XXX_DiscardUnknown() {
	xxx_messageInfo_FloatField.DiscardUnknown(m)
}

var xxx_messageInfo_FloatField proto.InternalMessageInfo

func (m *FloatField) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *FloatField) GetRelType() FieldRelationship {
	if m != nil {
		return m.RelType
	}
	return FieldRelationship_UNKNOWN_FIELD_REL
}

func (m *FloatField) GetRangeValue() float32 {
	if m != nil {
		return m.RangeValue
	}
	return 0
}

func (m *FloatField) GetSortDirection() SortDirection {
	if m != nil {
		return m.SortDirection
	}
	return SortDirection_NOT_SORTED
}

type DoubleField struct {
	Value                float64           `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	RelType              FieldRelationship `protobuf:"varint,2,opt,name=rel_type,json=relType,proto3,enum=epl.protobuf.FieldRelationship" json:"rel_type,omitempty"`
	RangeValue           float64           `protobuf:"fixed64,3,opt,name=range_value,json=rangeValue,proto3" json:"range_value,omitempty"`
	SortDirection        SortDirection     `protobuf:"varint,4,opt,name=sort_direction,json=sortDirection,proto3,enum=epl.protobuf.SortDirection" json:"sort_direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DoubleField) Reset()         { *m = DoubleField{} }
func (m *DoubleField) String() string { return proto.CompactTextString(m) }
func (*DoubleField) ProtoMessage()    {}
func (*DoubleField) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_78a5b0bbc1bbffce, []int{1}
}
func (m *DoubleField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleField.Unmarshal(m, b)
}
func (m *DoubleField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleField.Marshal(b, m, deterministic)
}
func (dst *DoubleField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleField.Merge(dst, src)
}
func (m *DoubleField) XXX_Size() int {
	return xxx_messageInfo_DoubleField.Size(m)
}
func (m *DoubleField) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleField.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleField proto.InternalMessageInfo

func (m *DoubleField) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *DoubleField) GetRelType() FieldRelationship {
	if m != nil {
		return m.RelType
	}
	return FieldRelationship_UNKNOWN_FIELD_REL
}

func (m *DoubleField) GetRangeValue() float64 {
	if m != nil {
		return m.RangeValue
	}
	return 0
}

func (m *DoubleField) GetSortDirection() SortDirection {
	if m != nil {
		return m.SortDirection
	}
	return SortDirection_NOT_SORTED
}

type StringField struct {
	Value                string            `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	RelType              FieldRelationship `protobuf:"varint,2,opt,name=rel_type,json=relType,proto3,enum=epl.protobuf.FieldRelationship" json:"rel_type,omitempty"`
	RangeValue           string            `protobuf:"bytes,3,opt,name=range_value,json=rangeValue,proto3" json:"range_value,omitempty"`
	SortDirection        SortDirection     `protobuf:"varint,4,opt,name=sort_direction,json=sortDirection,proto3,enum=epl.protobuf.SortDirection" json:"sort_direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StringField) Reset()         { *m = StringField{} }
func (m *StringField) String() string { return proto.CompactTextString(m) }
func (*StringField) ProtoMessage()    {}
func (*StringField) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_78a5b0bbc1bbffce, []int{2}
}
func (m *StringField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringField.Unmarshal(m, b)
}
func (m *StringField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringField.Marshal(b, m, deterministic)
}
func (dst *StringField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringField.Merge(dst, src)
}
func (m *StringField) XXX_Size() int {
	return xxx_messageInfo_StringField.Size(m)
}
func (m *StringField) XXX_DiscardUnknown() {
	xxx_messageInfo_StringField.DiscardUnknown(m)
}

var xxx_messageInfo_StringField proto.InternalMessageInfo

func (m *StringField) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *StringField) GetRelType() FieldRelationship {
	if m != nil {
		return m.RelType
	}
	return FieldRelationship_UNKNOWN_FIELD_REL
}

func (m *StringField) GetRangeValue() string {
	if m != nil {
		return m.RangeValue
	}
	return ""
}

func (m *StringField) GetSortDirection() SortDirection {
	if m != nil {
		return m.SortDirection
	}
	return SortDirection_NOT_SORTED
}

type TimestampField struct {
	Value                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	RelType              FieldRelationship    `protobuf:"varint,2,opt,name=rel_type,json=relType,proto3,enum=epl.protobuf.FieldRelationship" json:"rel_type,omitempty"`
	RangeValue           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=range_value,json=rangeValue,proto3" json:"range_value,omitempty"`
	SortDirection        SortDirection        `protobuf:"varint,4,opt,name=sort_direction,json=sortDirection,proto3,enum=epl.protobuf.SortDirection" json:"sort_direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TimestampField) Reset()         { *m = TimestampField{} }
func (m *TimestampField) String() string { return proto.CompactTextString(m) }
func (*TimestampField) ProtoMessage()    {}
func (*TimestampField) Descriptor() ([]byte, []int) {
	return fileDescriptor_query_78a5b0bbc1bbffce, []int{3}
}
func (m *TimestampField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimestampField.Unmarshal(m, b)
}
func (m *TimestampField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimestampField.Marshal(b, m, deterministic)
}
func (dst *TimestampField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimestampField.Merge(dst, src)
}
func (m *TimestampField) XXX_Size() int {
	return xxx_messageInfo_TimestampField.Size(m)
}
func (m *TimestampField) XXX_DiscardUnknown() {
	xxx_messageInfo_TimestampField.DiscardUnknown(m)
}

var xxx_messageInfo_TimestampField proto.InternalMessageInfo

func (m *TimestampField) GetValue() *timestamp.Timestamp {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *TimestampField) GetRelType() FieldRelationship {
	if m != nil {
		return m.RelType
	}
	return FieldRelationship_UNKNOWN_FIELD_REL
}

func (m *TimestampField) GetRangeValue() *timestamp.Timestamp {
	if m != nil {
		return m.RangeValue
	}
	return nil
}

func (m *TimestampField) GetSortDirection() SortDirection {
	if m != nil {
		return m.SortDirection
	}
	return SortDirection_NOT_SORTED
}

func init() {
	proto.RegisterType((*FloatField)(nil), "epl.protobuf.FloatField")
	proto.RegisterType((*DoubleField)(nil), "epl.protobuf.DoubleField")
	proto.RegisterType((*StringField)(nil), "epl.protobuf.StringField")
	proto.RegisterType((*TimestampField)(nil), "epl.protobuf.TimestampField")
	proto.RegisterEnum("epl.protobuf.SortDirection", SortDirection_name, SortDirection_value)
	proto.RegisterEnum("epl.protobuf.FieldRelationship", FieldRelationship_name, FieldRelationship_value)
}

func init() { proto.RegisterFile("epl/protobuf/query.proto", fileDescriptor_query_78a5b0bbc1bbffce) }

var fileDescriptor_query_78a5b0bbc1bbffce = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x1c, 0xc5, 0xe7, 0x6c, 0xc0, 0xfa, 0xef, 0x5a, 0x5c, 0xaf, 0x88, 0x6a, 0x1c, 0x5a, 0xed, 0x34,
	0x0d, 0x91, 0xa0, 0x71, 0x03, 0x09, 0xd1, 0x12, 0xb7, 0x9a, 0xa8, 0xd2, 0x36, 0xc9, 0x40, 0xe2,
	0x12, 0xa5, 0x9d, 0xc9, 0x22, 0xb9, 0x75, 0x70, 0x1d, 0xa4, 0xde, 0xf8, 0x2c, 0x7c, 0x15, 0xb8,
	0xf1, 0xa1, 0x40, 0x89, 0xdb, 0x35, 0xd5, 0xa6, 0x9d, 0xda, 0xe3, 0x7b, 0x7e, 0xfe, 0x3f, 0xff,
	0x2c, 0xcb, 0xd0, 0x60, 0x09, 0xb7, 0x12, 0x29, 0x94, 0x18, 0xa7, 0xdf, 0xac, 0xef, 0x29, 0x93,
	0x0b, 0x33, 0x97, 0xe4, 0x88, 0x25, 0xdc, 0x5c, 0xad, 0x9c, 0x34, 0x23, 0x21, 0x22, 0xce, 0xd6,
	0x51, 0x15, 0x4f, 0xd9, 0x5c, 0x85, 0xd3, 0x44, 0x67, 0x4e, 0x7f, 0x23, 0x80, 0x2e, 0x17, 0xa1,
	0xea, 0xc6, 0x8c, 0x5f, 0x93, 0x3a, 0x3c, 0xfa, 0x11, 0xf2, 0x94, 0x35, 0x50, 0x0b, 0x9d, 0x19,
	0xae, 0x16, 0xe4, 0x2d, 0x1c, 0x4a, 0xc6, 0x03, 0xb5, 0x48, 0x58, 0xc3, 0x68, 0xa1, 0xb3, 0xea,
	0x45, 0xd3, 0x2c, 0xd6, 0x98, 0xf9, 0x66, 0x97, 0xf1, 0x50, 0xc5, 0x62, 0x36, 0xbf, 0x89, 0x13,
	0xf7, 0x89, 0x64, 0xdc, 0x5f, 0x24, 0x8c, 0x34, 0xa1, 0x2c, 0xc3, 0x59, 0xc4, 0x02, 0x3d, 0x77,
	0x3f, 0x9f, 0x0b, 0xb9, 0xf5, 0x39, 0x1f, 0xde, 0x81, 0xea, 0x5c, 0x48, 0x15, 0x5c, 0xc7, 0x92,
	0x4d, 0xb2, 0xfd, 0x8d, 0x83, 0xbc, 0xe2, 0xc5, 0x66, 0x85, 0x27, 0xa4, 0xb2, 0x57, 0x11, 0xb7,
	0x32, 0x2f, 0xca, 0xd3, 0x3f, 0x08, 0xca, 0xb6, 0x48, 0xc7, 0x9c, 0xdd, 0x83, 0x81, 0x76, 0x84,
	0x81, 0x76, 0x82, 0xe1, 0x29, 0x19, 0xcf, 0xa2, 0x7b, 0x30, 0x4a, 0x3b, 0xc2, 0x28, 0x6d, 0x1d,
	0xe3, 0x1f, 0x82, 0xaa, 0xbf, 0x7a, 0x67, 0x9a, 0xe4, 0x75, 0x91, 0xa4, 0x7c, 0x71, 0x62, 0xea,
	0x77, 0xb9, 0x1e, 0x78, 0x9b, 0xdf, 0x06, 0xe5, 0xbb, 0xbb, 0x94, 0x0f, 0x77, 0x6e, 0xf9, 0x06,
	0xce, 0xdf, 0x43, 0x65, 0x63, 0x9d, 0x54, 0x01, 0x9c, 0x81, 0x1f, 0x78, 0x03, 0xd7, 0xa7, 0x36,
	0xde, 0xcb, 0xb4, 0x4d, 0xbd, 0x8f, 0xd4, 0xb1, 0x2f, 0x9d, 0x1e, 0x46, 0xa4, 0x02, 0xa5, 0xf6,
	0xad, 0x34, 0xce, 0xff, 0x22, 0xa8, 0xdd, 0xe1, 0x23, 0xcf, 0xa0, 0x76, 0xe5, 0x7c, 0x72, 0x06,
	0x5f, 0x9c, 0xa0, 0x7b, 0x49, 0xfb, 0x76, 0xe0, 0xd2, 0x3e, 0xde, 0x23, 0x18, 0x8e, 0xb4, 0xa4,
	0xa3, 0xab, 0x76, 0xdf, 0xc3, 0x06, 0x39, 0x86, 0xa7, 0xda, 0xc9, 0x3a, 0x73, 0x17, 0x1f, 0x90,
	0x3a, 0x60, 0x6d, 0xf6, 0xa9, 0xe7, 0x2d, 0xdd, 0x43, 0xf2, 0x1c, 0x8e, 0xb5, 0xdb, 0x73, 0x69,
	0xdb, 0xa7, 0xee, 0x72, 0x01, 0x67, 0x27, 0x5c, 0xc7, 0x71, 0x8b, 0xd4, 0xa0, 0xb2, 0x11, 0xc4,
	0x1f, 0x08, 0x86, 0xf2, 0xf2, 0x1c, 0x6d, 0xa7, 0x47, 0xf1, 0x4f, 0x44, 0xea, 0xc5, 0xe2, 0xa5,
	0x6b, 0x74, 0x3c, 0xc0, 0x13, 0x31, 0xdd, 0xb8, 0xbe, 0x0e, 0x8c, 0xb2, 0x3f, 0x6b, 0x98, 0xc9,
	0x21, 0xfa, 0xfa, 0x32, 0x8a, 0xd5, 0x4d, 0x3a, 0x36, 0x27, 0x62, 0x6a, 0x45, 0x4c, 0xbc, 0x8a,
	0x64, 0x32, 0xb1, 0xc2, 0x24, 0xb6, 0x22, 0xc1, 0xc3, 0x59, 0x64, 0x15, 0x7f, 0xbb, 0x5f, 0xc6,
	0xfe, 0x68, 0xd8, 0x19, 0x3f, 0xce, 0xf5, 0x9b, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x07,
	0x54, 0xb7, 0x0a, 0x05, 0x00, 0x00,
}
