// Code generated by protoc-gen-go. DO NOT EDIT.
// source: epl/protobuf/stac.proto

package protobuf // import "github.com/geo-grpc/api/golang/epl/protobuf"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AssetType int32

const (
	AssetType_UNKNOWN_ASSET AssetType = 0
	AssetType_JPEG          AssetType = 1
	// geotiff https://www.gdal.org/frmt_gtiff.html
	AssetType_GEOTIFF AssetType = 2
	// Limited Error Raster Compression
	AssetType_LERC AssetType = 3
	// metadata raster file https://github.com/nasa-gibs/mrf/blob/master/spec/mrf_spec.md#mrf-metadata-file-mrf
	AssetType_MRF AssetType = 4
	// metadata raster file index https://github.com/nasa-gibs/mrf/blob/master/spec/mrf_spec.md#mrf-index-file-idx
	AssetType_MRF_IDX AssetType = 5
	AssetType_MRF_XML AssetType = 6
	// cloud optimized geotiff https://www.cogeo.org/
	AssetType_CO_GEOTIFF AssetType = 7
	AssetType_RAW        AssetType = 8
	AssetType_THUMBNAIL  AssetType = 9
	AssetType_TIFF       AssetType = 10
	AssetType_JPEG_2000  AssetType = 11
	AssetType_XML        AssetType = 12
)

var AssetType_name = map[int32]string{
	0:  "UNKNOWN_ASSET",
	1:  "JPEG",
	2:  "GEOTIFF",
	3:  "LERC",
	4:  "MRF",
	5:  "MRF_IDX",
	6:  "MRF_XML",
	7:  "CO_GEOTIFF",
	8:  "RAW",
	9:  "THUMBNAIL",
	10: "TIFF",
	11: "JPEG_2000",
	12: "XML",
}
var AssetType_value = map[string]int32{
	"UNKNOWN_ASSET": 0,
	"JPEG":          1,
	"GEOTIFF":       2,
	"LERC":          3,
	"MRF":           4,
	"MRF_IDX":       5,
	"MRF_XML":       6,
	"CO_GEOTIFF":    7,
	"RAW":           8,
	"THUMBNAIL":     9,
	"TIFF":          10,
	"JPEG_2000":     11,
	"XML":           12,
}

func (x AssetType) String() string {
	return proto.EnumName(AssetType_name, int32(x))
}
func (AssetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_stac_088418add3b66529, []int{0}
}

type CloudPlatform int32

const (
	CloudPlatform_UNKNOWN_CLOUD_PLATFORM CloudPlatform = 0
	CloudPlatform_AWS                    CloudPlatform = 1
	CloudPlatform_GCP                    CloudPlatform = 2
	CloudPlatform_AZURE                  CloudPlatform = 3
)

var CloudPlatform_name = map[int32]string{
	0: "UNKNOWN_CLOUD_PLATFORM",
	1: "AWS",
	2: "GCP",
	3: "AZURE",
}
var CloudPlatform_value = map[string]int32{
	"UNKNOWN_CLOUD_PLATFORM": 0,
	"AWS":                    1,
	"GCP":                    2,
	"AZURE":                  3,
}

func (x CloudPlatform) String() string {
	return proto.EnumName(CloudPlatform_name, int32(x))
}
func (CloudPlatform) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_stac_088418add3b66529, []int{1}
}

type Sar_Platform int32

const (
	Sar_UNKNOWN_PLATFORM Sar_Platform = 0
	Sar_ENVISAT          Sar_Platform = 1
	Sar_SENTINEL_1A      Sar_Platform = 2
)

var Sar_Platform_name = map[int32]string{
	0: "UNKNOWN_PLATFORM",
	1: "ENVISAT",
	2: "SENTINEL_1A",
}
var Sar_Platform_value = map[string]int32{
	"UNKNOWN_PLATFORM": 0,
	"ENVISAT":          1,
	"SENTINEL_1A":      2,
}

func (x Sar_Platform) String() string {
	return proto.EnumName(Sar_Platform_name, int32(x))
}
func (Sar_Platform) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_stac_088418add3b66529, []int{6, 0}
}

type Sar_Instrument int32

const (
	Sar_UNKNOWN_INSTRUMENT Sar_Instrument = 0
)

var Sar_Instrument_name = map[int32]string{
	0: "UNKNOWN_INSTRUMENT",
}
var Sar_Instrument_value = map[string]int32{
	"UNKNOWN_INSTRUMENT": 0,
}

func (x Sar_Instrument) String() string {
	return proto.EnumName(Sar_Instrument_name, int32(x))
}
func (Sar_Instrument) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_stac_088418add3b66529, []int{6, 1}
}

type Eo_Platform int32

const (
	Eo_UNKNOWN_PLATFORM Eo_Platform = 0
	Eo_LANDSAT_1        Eo_Platform = 2
	Eo_LANDSAT_2        Eo_Platform = 4
	Eo_LANDSAT_3        Eo_Platform = 8
	Eo_LANDSAT_123      Eo_Platform = 14
	Eo_LANDSAT_4        Eo_Platform = 16
	Eo_LANDSAT_5        Eo_Platform = 32
	Eo_LANDSAT_45       Eo_Platform = 48
	Eo_LANDSAT_7        Eo_Platform = 64
	Eo_LANDSAT_8        Eo_Platform = 128
	// swiftera platform
	Eo_SWIFT_2 Eo_Platform = 256
)

var Eo_Platform_name = map[int32]string{
	0:   "UNKNOWN_PLATFORM",
	2:   "LANDSAT_1",
	4:   "LANDSAT_2",
	8:   "LANDSAT_3",
	14:  "LANDSAT_123",
	16:  "LANDSAT_4",
	32:  "LANDSAT_5",
	48:  "LANDSAT_45",
	64:  "LANDSAT_7",
	128: "LANDSAT_8",
	256: "SWIFT_2",
}
var Eo_Platform_value = map[string]int32{
	"UNKNOWN_PLATFORM": 0,
	"LANDSAT_1":        2,
	"LANDSAT_2":        4,
	"LANDSAT_3":        8,
	"LANDSAT_123":      14,
	"LANDSAT_4":        16,
	"LANDSAT_5":        32,
	"LANDSAT_45":       48,
	"LANDSAT_7":        64,
	"LANDSAT_8":        128,
	"SWIFT_2":          256,
}

func (x Eo_Platform) String() string {
	return proto.EnumName(Eo_Platform_name, int32(x))
}
func (Eo_Platform) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_stac_088418add3b66529, []int{7, 0}
}

type Eo_Instrument int32

const (
	Eo_UNKNOWN_INSTRUMENT Eo_Instrument = 0
	Eo_OLI                Eo_Instrument = 2
	Eo_TIRS               Eo_Instrument = 4
	Eo_OLI_TIRS           Eo_Instrument = 6
	// swiftera instrument
	Eo_POM_1 Eo_Instrument = 8
	Eo_TM    Eo_Instrument = 16
	Eo_ETM   Eo_Instrument = 32
	Eo_MSS   Eo_Instrument = 64
)

var Eo_Instrument_name = map[int32]string{
	0:  "UNKNOWN_INSTRUMENT",
	2:  "OLI",
	4:  "TIRS",
	6:  "OLI_TIRS",
	8:  "POM_1",
	16: "TM",
	32: "ETM",
	64: "MSS",
}
var Eo_Instrument_value = map[string]int32{
	"UNKNOWN_INSTRUMENT": 0,
	"OLI":                2,
	"TIRS":               4,
	"OLI_TIRS":           6,
	"POM_1":              8,
	"TM":                 16,
	"ETM":                32,
	"MSS":                64,
}

func (x Eo_Instrument) String() string {
	return proto.EnumName(Eo_Instrument_name, int32(x))
}
func (Eo_Instrument) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_stac_088418add3b66529, []int{7, 1}
}

type Eo_Constellation int32

const (
	Eo_UNKNOWN_CONSTELLATION Eo_Constellation = 0
	Eo_LANDSAT               Eo_Constellation = 2
	Eo_NAIP                  Eo_Constellation = 4
	// spanish aerial dataset
	Eo_PNOA Eo_Constellation = 8
	// swiftera dataset
	Eo_SWIFT Eo_Constellation = 16
)

var Eo_Constellation_name = map[int32]string{
	0:  "UNKNOWN_CONSTELLATION",
	2:  "LANDSAT",
	4:  "NAIP",
	8:  "PNOA",
	16: "SWIFT",
}
var Eo_Constellation_value = map[string]int32{
	"UNKNOWN_CONSTELLATION": 0,
	"LANDSAT":               2,
	"NAIP":                  4,
	"PNOA":                  8,
	"SWIFT":                 16,
}

func (x Eo_Constellation) String() string {
	return proto.EnumName(Eo_Constellation_name, int32(x))
}
func (Eo_Constellation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_stac_088418add3b66529, []int{7, 2}
}

type Eo_Band int32

const (
	Eo_UNKNOWN_BAND Eo_Band = 0
	Eo_COASTAL      Eo_Band = 2
	Eo_BLUE         Eo_Band = 4
	Eo_GREEN        Eo_Band = 8
	Eo_RED          Eo_Band = 16
	Eo_RGB          Eo_Band = 28
	Eo_NIR          Eo_Band = 32
	// special case for landsat 1-3
	Eo_NIR_2        Eo_Band = 33
	Eo_RGBIR        Eo_Band = 60
	Eo_SWIR_1       Eo_Band = 64
	Eo_SWIR_2       Eo_Band = 128
	Eo_PANCHROMATIC Eo_Band = 256
	Eo_CIRRUS       Eo_Band = 512
	Eo_LWIR_1       Eo_Band = 1024
	Eo_LWIR_2       Eo_Band = 2048
)

var Eo_Band_name = map[int32]string{
	0:    "UNKNOWN_BAND",
	2:    "COASTAL",
	4:    "BLUE",
	8:    "GREEN",
	16:   "RED",
	28:   "RGB",
	32:   "NIR",
	33:   "NIR_2",
	60:   "RGBIR",
	64:   "SWIR_1",
	128:  "SWIR_2",
	256:  "PANCHROMATIC",
	512:  "CIRRUS",
	1024: "LWIR_1",
	2048: "LWIR_2",
}
var Eo_Band_value = map[string]int32{
	"UNKNOWN_BAND": 0,
	"COASTAL":      2,
	"BLUE":         4,
	"GREEN":        8,
	"RED":          16,
	"RGB":          28,
	"NIR":          32,
	"NIR_2":        33,
	"RGBIR":        60,
	"SWIR_1":       64,
	"SWIR_2":       128,
	"PANCHROMATIC": 256,
	"CIRRUS":       512,
	"LWIR_1":       1024,
	"LWIR_2":       2048,
}

func (x Eo_Band) String() string {
	return proto.EnumName(Eo_Band_name, int32(x))
}
func (Eo_Band) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_stac_088418add3b66529, []int{7, 3}
}

// *
// Spatio-Temporal Asset Catalog Item. This data item has a spatial and temporal extent. It has a unique identifier
// downloadable assets. It may have an extension with details beyond the spatial and temporal extents. It may have
// additional properties in the properties field
type StacItem struct {
	// Provider identifier. As most geospatial assets are already defined by some identification scheme by the data provider it is recommended to simply use that ID. Data providers are advised to include sufficient information to make their IDs globally unique, including things like unique satellite IDs.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// the spatial shape of the item. must have a spatial reference defined.
	Geometry *GeometryData `protobuf:"bytes,3,opt,name=geometry,proto3" json:"geometry,omitempty"`
	// the bounding box of the spatial shape of the item. must have a spatial reference defined.
	Bbox *EnvelopeData `protobuf:"bytes,4,opt,name=bbox,proto3" json:"bbox,omitempty"`
	// the properties of an item that are not defined within the stac specification. Requires marshalling and un-marshalling https://developers.google.com/protocol-buffers/docs/proto3#any
	Properties *any.Any `protobuf:"bytes,5,opt,name=properties,proto3" json:"properties,omitempty"`
	// Dictionary of asset objects that can be downloaded, each with a unique key. Some pre-defined keys are listed in the chapter 'Asset types'.
	Assets map[string]*Asset `protobuf:"bytes,7,rep,name=assets,proto3" json:"assets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The searchable date and time of the assets, in UTC
	Datetime *timestamp.Timestamp `protobuf:"bytes,8,opt,name=datetime,proto3" json:"datetime,omitempty"`
	// (optional) A human readable title describing the item.
	Title string `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	// (optional) The id of the STAC Collection this Item references to (see collection relation type below). This field is required if such a relation type is present. This field provides an easy way for a user to search for any Items that belong in a specified Collection.
	Collection string `protobuf:"bytes,10,opt,name=collection,proto3" json:"collection,omitempty"`
	// timestamp at which data was observed (optional if datetime set)
	Observed *timestamp.Timestamp `protobuf:"bytes,11,opt,name=observed,proto3" json:"observed,omitempty"`
	// timestamp when it was processed (when assets were generated)
	Processed *timestamp.Timestamp `protobuf:"bytes,12,opt,name=processed,proto3" json:"processed,omitempty"`
	// last timestamp when stac metadata itself was updated
	Updated *timestamp.Timestamp `protobuf:"bytes,13,opt,name=updated,proto3" json:"updated,omitempty"`
	// electro-optical data message
	Eo *Eo `protobuf:"bytes,14,opt,name=eo,proto3" json:"eo,omitempty"`
	// Synthetic Aperture Radar data message
	Sar *Sar `protobuf:"bytes,15,opt,name=sar,proto3" json:"sar,omitempty"`
	// Date time range
	Dtr                  *Dtr     `protobuf:"bytes,16,opt,name=dtr,proto3" json:"dtr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StacItem) Reset()         { *m = StacItem{} }
func (m *StacItem) String() string { return proto.CompactTextString(m) }
func (*StacItem) ProtoMessage()    {}
func (*StacItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_stac_088418add3b66529, []int{0}
}
func (m *StacItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StacItem.Unmarshal(m, b)
}
func (m *StacItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StacItem.Marshal(b, m, deterministic)
}
func (dst *StacItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StacItem.Merge(dst, src)
}
func (m *StacItem) XXX_Size() int {
	return xxx_messageInfo_StacItem.Size(m)
}
func (m *StacItem) XXX_DiscardUnknown() {
	xxx_messageInfo_StacItem.DiscardUnknown(m)
}

var xxx_messageInfo_StacItem proto.InternalMessageInfo

func (m *StacItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StacItem) GetGeometry() *GeometryData {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *StacItem) GetBbox() *EnvelopeData {
	if m != nil {
		return m.Bbox
	}
	return nil
}

func (m *StacItem) GetProperties() *any.Any {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *StacItem) GetAssets() map[string]*Asset {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *StacItem) GetDatetime() *timestamp.Timestamp {
	if m != nil {
		return m.Datetime
	}
	return nil
}

func (m *StacItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *StacItem) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *StacItem) GetObserved() *timestamp.Timestamp {
	if m != nil {
		return m.Observed
	}
	return nil
}

func (m *StacItem) GetProcessed() *timestamp.Timestamp {
	if m != nil {
		return m.Processed
	}
	return nil
}

func (m *StacItem) GetUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

func (m *StacItem) GetEo() *Eo {
	if m != nil {
		return m.Eo
	}
	return nil
}

func (m *StacItem) GetSar() *Sar {
	if m != nil {
		return m.Sar
	}
	return nil
}

func (m *StacItem) GetDtr() *Dtr {
	if m != nil {
		return m.Dtr
	}
	return nil
}

// *
// message for making a request for stac items.
type StacRequest struct {
	// if id matches, return the one matching stac item
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// search by the spatial extent as defined by geometry
	Geometry *GeometryData `protobuf:"bytes,2,opt,name=geometry,proto3" json:"geometry,omitempty"`
	// search by the spatial extent as defined by the envelope bounds
	Bbox *EnvelopeData `protobuf:"bytes,3,opt,name=bbox,proto3" json:"bbox,omitempty"`
	// search by a geometry request. this sends a geometry operator to a geometry service, and the returned geometry is in turn used as the spatial extent
	GeometryRequest *GeometryRequest `protobuf:"bytes,4,opt,name=geometry_request,json=geometryRequest,proto3" json:"geometry_request,omitempty"`
	// search by properties specified by user using a request object known by user and the Any marshalling pattern
	Properties *any.Any `protobuf:"bytes,5,opt,name=properties,proto3" json:"properties,omitempty"`
	// search for the datetime that matched by bounds defined by the exact timestamp or a range of timestamp
	Datetime *TimestampField `protobuf:"bytes,6,opt,name=datetime,proto3" json:"datetime,omitempty"`
	// search for the moment the data was observed by bounds defined by the exact timestamp or a range of timestamp
	Observed *TimestampField `protobuf:"bytes,7,opt,name=observed,proto3" json:"observed,omitempty"`
	// search for the moment the data was processed by bounds defined by the exact timestamp or a range of timestamp
	Processed *TimestampField `protobuf:"bytes,8,opt,name=processed,proto3" json:"processed,omitempty"`
	// search for the moment the stac item metadata was updated by bounds defined by the exact timestamp or a range of timestamp
	Updated *TimestampField `protobuf:"bytes,9,opt,name=updated,proto3" json:"updated,omitempty"`
	// use certain electro-optical search parameters in your query
	Eo *EoRequest `protobuf:"bytes,10,opt,name=eo,proto3" json:"eo,omitempty"`
	// limit the number of results returned
	Limit uint32 `protobuf:"varint,11,opt,name=limit,proto3" json:"limit,omitempty"`
	// the offset from which the query should start
	Offset               uint64   `protobuf:"varint,12,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StacRequest) Reset()         { *m = StacRequest{} }
func (m *StacRequest) String() string { return proto.CompactTextString(m) }
func (*StacRequest) ProtoMessage()    {}
func (*StacRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stac_088418add3b66529, []int{1}
}
func (m *StacRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StacRequest.Unmarshal(m, b)
}
func (m *StacRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StacRequest.Marshal(b, m, deterministic)
}
func (dst *StacRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StacRequest.Merge(dst, src)
}
func (m *StacRequest) XXX_Size() int {
	return xxx_messageInfo_StacRequest.Size(m)
}
func (m *StacRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StacRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StacRequest proto.InternalMessageInfo

func (m *StacRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StacRequest) GetGeometry() *GeometryData {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *StacRequest) GetBbox() *EnvelopeData {
	if m != nil {
		return m.Bbox
	}
	return nil
}

func (m *StacRequest) GetGeometryRequest() *GeometryRequest {
	if m != nil {
		return m.GeometryRequest
	}
	return nil
}

func (m *StacRequest) GetProperties() *any.Any {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *StacRequest) GetDatetime() *TimestampField {
	if m != nil {
		return m.Datetime
	}
	return nil
}

func (m *StacRequest) GetObserved() *TimestampField {
	if m != nil {
		return m.Observed
	}
	return nil
}

func (m *StacRequest) GetProcessed() *TimestampField {
	if m != nil {
		return m.Processed
	}
	return nil
}

func (m *StacRequest) GetUpdated() *TimestampField {
	if m != nil {
		return m.Updated
	}
	return nil
}

func (m *StacRequest) GetEo() *EoRequest {
	if m != nil {
		return m.Eo
	}
	return nil
}

func (m *StacRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *StacRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

// Right now this isn't included in the response as it's a bit messy
type BandDetails struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CommonName           string               `protobuf:"bytes,2,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Gsd                  *wrappers.FloatValue `protobuf:"bytes,4,opt,name=gsd,proto3" json:"gsd,omitempty"`
	Accuracy             *wrappers.FloatValue `protobuf:"bytes,5,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	CenterWavelength     *wrappers.FloatValue `protobuf:"bytes,6,opt,name=center_wavelength,json=centerWavelength,proto3" json:"center_wavelength,omitempty"`
	FullWidthHalfMax     *wrappers.FloatValue `protobuf:"bytes,7,opt,name=full_width_half_max,json=fullWidthHalfMax,proto3" json:"full_width_half_max,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BandDetails) Reset()         { *m = BandDetails{} }
func (m *BandDetails) String() string { return proto.CompactTextString(m) }
func (*BandDetails) ProtoMessage()    {}
func (*BandDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_stac_088418add3b66529, []int{2}
}
func (m *BandDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BandDetails.Unmarshal(m, b)
}
func (m *BandDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BandDetails.Marshal(b, m, deterministic)
}
func (dst *BandDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BandDetails.Merge(dst, src)
}
func (m *BandDetails) XXX_Size() int {
	return xxx_messageInfo_BandDetails.Size(m)
}
func (m *BandDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_BandDetails.DiscardUnknown(m)
}

var xxx_messageInfo_BandDetails proto.InternalMessageInfo

func (m *BandDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BandDetails) GetCommonName() string {
	if m != nil {
		return m.CommonName
	}
	return ""
}

func (m *BandDetails) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BandDetails) GetGsd() *wrappers.FloatValue {
	if m != nil {
		return m.Gsd
	}
	return nil
}

func (m *BandDetails) GetAccuracy() *wrappers.FloatValue {
	if m != nil {
		return m.Accuracy
	}
	return nil
}

func (m *BandDetails) GetCenterWavelength() *wrappers.FloatValue {
	if m != nil {
		return m.CenterWavelength
	}
	return nil
}

func (m *BandDetails) GetFullWidthHalfMax() *wrappers.FloatValue {
	if m != nil {
		return m.FullWidthHalfMax
	}
	return nil
}

// *
// message for an asset of a stac item.
type Asset struct {
	// href for downloading item
	Href string `protobuf:"bytes,1,opt,name=href,proto3" json:"href,omitempty"`
	// asset type
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// band(s) of data in asset. https://github.com/radiantearth/stac-spec/blob/612ee4fb4f979c049d2416e7f5374a5301b8a277/extensions/eo/README.md
	EoBands Eo_Band `protobuf:"varint,3,opt,name=eo_bands,json=eoBands,proto3,enum=epl.protobuf.Eo_Band" json:"eo_bands,omitempty"`
	// enum for asset type
	AssetType AssetType `protobuf:"varint,4,opt,name=asset_type,json=assetType,proto3,enum=epl.protobuf.AssetType" json:"asset_type,omitempty"`
	// cloud platform enum (Google cloud, Azure, etc)
	CloudPlatform CloudPlatform `protobuf:"varint,5,opt,name=cloud_platform,json=cloudPlatform,proto3,enum=epl.protobuf.CloudPlatform" json:"cloud_platform,omitempty"`
	// manager of the bucket
	BucketManager string `protobuf:"bytes,6,opt,name=bucket_manager,json=bucketManager,proto3" json:"bucket_manager,omitempty"`
	// bucket region. useful when concerned about egress
	BucketRegion string `protobuf:"bytes,7,opt,name=bucket_region,json=bucketRegion,proto3" json:"bucket_region,omitempty"`
	// bucket name
	Bucket string `protobuf:"bytes,8,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// path to the object in the bucket
	ObjectPath string `protobuf:"bytes,9,opt,name=object_path,json=objectPath,proto3" json:"object_path,omitempty"`
	// requester_pays pertains to egress cost. Some buckets are hosted with the egress costs assigned to the requester. some hosts pay the regress costs for the requester.
	RequesterPays        bool     `protobuf:"varint,10,opt,name=requester_pays,json=requesterPays,proto3" json:"requester_pays,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_stac_088418add3b66529, []int{3}
}
func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (dst *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(dst, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetHref() string {
	if m != nil {
		return m.Href
	}
	return ""
}

func (m *Asset) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Asset) GetEoBands() Eo_Band {
	if m != nil {
		return m.EoBands
	}
	return Eo_UNKNOWN_BAND
}

func (m *Asset) GetAssetType() AssetType {
	if m != nil {
		return m.AssetType
	}
	return AssetType_UNKNOWN_ASSET
}

func (m *Asset) GetCloudPlatform() CloudPlatform {
	if m != nil {
		return m.CloudPlatform
	}
	return CloudPlatform_UNKNOWN_CLOUD_PLATFORM
}

func (m *Asset) GetBucketManager() string {
	if m != nil {
		return m.BucketManager
	}
	return ""
}

func (m *Asset) GetBucketRegion() string {
	if m != nil {
		return m.BucketRegion
	}
	return ""
}

func (m *Asset) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *Asset) GetObjectPath() string {
	if m != nil {
		return m.ObjectPath
	}
	return ""
}

func (m *Asset) GetRequesterPays() bool {
	if m != nil {
		return m.RequesterPays
	}
	return false
}

type Dtr struct {
	Start                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Dtr) Reset()         { *m = Dtr{} }
func (m *Dtr) String() string { return proto.CompactTextString(m) }
func (*Dtr) ProtoMessage()    {}
func (*Dtr) Descriptor() ([]byte, []int) {
	return fileDescriptor_stac_088418add3b66529, []int{4}
}
func (m *Dtr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dtr.Unmarshal(m, b)
}
func (m *Dtr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dtr.Marshal(b, m, deterministic)
}
func (dst *Dtr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dtr.Merge(dst, src)
}
func (m *Dtr) XXX_Size() int {
	return xxx_messageInfo_Dtr.Size(m)
}
func (m *Dtr) XXX_DiscardUnknown() {
	xxx_messageInfo_Dtr.DiscardUnknown(m)
}

var xxx_messageInfo_Dtr proto.InternalMessageInfo

func (m *Dtr) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Dtr) GetEnd() *timestamp.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

// *
// response message for insertion and updates to stac db
type StacUpsertResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode           int32    `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	DataId               string   `protobuf:"bytes,3,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StacUpsertResponse) Reset()         { *m = StacUpsertResponse{} }
func (m *StacUpsertResponse) String() string { return proto.CompactTextString(m) }
func (*StacUpsertResponse) ProtoMessage()    {}
func (*StacUpsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stac_088418add3b66529, []int{5}
}
func (m *StacUpsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StacUpsertResponse.Unmarshal(m, b)
}
func (m *StacUpsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StacUpsertResponse.Marshal(b, m, deterministic)
}
func (dst *StacUpsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StacUpsertResponse.Merge(dst, src)
}
func (m *StacUpsertResponse) XXX_Size() int {
	return xxx_messageInfo_StacUpsertResponse.Size(m)
}
func (m *StacUpsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StacUpsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StacUpsertResponse proto.InternalMessageInfo

func (m *StacUpsertResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StacUpsertResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *StacUpsertResponse) GetDataId() string {
	if m != nil {
		return m.DataId
	}
	return ""
}

// *
// place holder for SAR
type Sar struct {
	Platform             Sar_Platform `protobuf:"varint,1,opt,name=platform,proto3,enum=epl.protobuf.Sar_Platform" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Sar) Reset()         { *m = Sar{} }
func (m *Sar) String() string { return proto.CompactTextString(m) }
func (*Sar) ProtoMessage()    {}
func (*Sar) Descriptor() ([]byte, []int) {
	return fileDescriptor_stac_088418add3b66529, []int{6}
}
func (m *Sar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sar.Unmarshal(m, b)
}
func (m *Sar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sar.Marshal(b, m, deterministic)
}
func (dst *Sar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sar.Merge(dst, src)
}
func (m *Sar) XXX_Size() int {
	return xxx_messageInfo_Sar.Size(m)
}
func (m *Sar) XXX_DiscardUnknown() {
	xxx_messageInfo_Sar.DiscardUnknown(m)
}

var xxx_messageInfo_Sar proto.InternalMessageInfo

func (m *Sar) GetPlatform() Sar_Platform {
	if m != nil {
		return m.Platform
	}
	return Sar_UNKNOWN_PLATFORM
}

// *
// message for electro optical details of stac items.
type Eo struct {
	// epsg code for the spatial reference of the data
	Epsg uint32 `protobuf:"varint,1,opt,name=epsg,proto3" json:"epsg,omitempty"`
	// platform from which the data was collected
	Platform Eo_Platform `protobuf:"varint,2,opt,name=platform,proto3,enum=epl.protobuf.Eo_Platform" json:"platform,omitempty"`
	// instrument which collected the data
	Instrument Eo_Instrument `protobuf:"varint,3,opt,name=instrument,proto3,enum=epl.protobuf.Eo_Instrument" json:"instrument,omitempty"`
	// constellation of data collectors
	Constellation Eo_Constellation `protobuf:"varint,4,opt,name=constellation,proto3,enum=epl.protobuf.Eo_Constellation" json:"constellation,omitempty"`
	// sun azimuth (at point of sensor?)
	SunAzimuth *wrappers.FloatValue `protobuf:"bytes,5,opt,name=sun_azimuth,json=sunAzimuth,proto3" json:"sun_azimuth,omitempty"`
	// sun elevation (at point of sensor?)
	SunElevation *wrappers.FloatValue `protobuf:"bytes,6,opt,name=sun_elevation,json=sunElevation,proto3" json:"sun_elevation,omitempty"`
	// ground sampling distance
	Gsd *wrappers.FloatValue `protobuf:"bytes,7,opt,name=gsd,proto3" json:"gsd,omitempty"`
	// off nadir angle of data
	OffNadir *wrappers.FloatValue `protobuf:"bytes,8,opt,name=off_nadir,json=offNadir,proto3" json:"off_nadir,omitempty"`
	// azimuth of the collection platform when sensor collected data (top of image in direction of azimuth)
	Azimuth *wrappers.FloatValue `protobuf:"bytes,9,opt,name=azimuth,proto3" json:"azimuth,omitempty"`
	// percent cloud cover. 0 no clouds, 100 completely covered
	CloudCover *wrappers.FloatValue `protobuf:"bytes,10,opt,name=cloud_cover,json=cloudCover,proto3" json:"cloud_cover,omitempty"`
	// bands of data
	Bands                Eo_Band  `protobuf:"varint,11,opt,name=bands,proto3,enum=epl.protobuf.Eo_Band" json:"bands,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Eo) Reset()         { *m = Eo{} }
func (m *Eo) String() string { return proto.CompactTextString(m) }
func (*Eo) ProtoMessage()    {}
func (*Eo) Descriptor() ([]byte, []int) {
	return fileDescriptor_stac_088418add3b66529, []int{7}
}
func (m *Eo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Eo.Unmarshal(m, b)
}
func (m *Eo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Eo.Marshal(b, m, deterministic)
}
func (dst *Eo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Eo.Merge(dst, src)
}
func (m *Eo) XXX_Size() int {
	return xxx_messageInfo_Eo.Size(m)
}
func (m *Eo) XXX_DiscardUnknown() {
	xxx_messageInfo_Eo.DiscardUnknown(m)
}

var xxx_messageInfo_Eo proto.InternalMessageInfo

func (m *Eo) GetEpsg() uint32 {
	if m != nil {
		return m.Epsg
	}
	return 0
}

func (m *Eo) GetPlatform() Eo_Platform {
	if m != nil {
		return m.Platform
	}
	return Eo_UNKNOWN_PLATFORM
}

func (m *Eo) GetInstrument() Eo_Instrument {
	if m != nil {
		return m.Instrument
	}
	return Eo_UNKNOWN_INSTRUMENT
}

func (m *Eo) GetConstellation() Eo_Constellation {
	if m != nil {
		return m.Constellation
	}
	return Eo_UNKNOWN_CONSTELLATION
}

func (m *Eo) GetSunAzimuth() *wrappers.FloatValue {
	if m != nil {
		return m.SunAzimuth
	}
	return nil
}

func (m *Eo) GetSunElevation() *wrappers.FloatValue {
	if m != nil {
		return m.SunElevation
	}
	return nil
}

func (m *Eo) GetGsd() *wrappers.FloatValue {
	if m != nil {
		return m.Gsd
	}
	return nil
}

func (m *Eo) GetOffNadir() *wrappers.FloatValue {
	if m != nil {
		return m.OffNadir
	}
	return nil
}

func (m *Eo) GetAzimuth() *wrappers.FloatValue {
	if m != nil {
		return m.Azimuth
	}
	return nil
}

func (m *Eo) GetCloudCover() *wrappers.FloatValue {
	if m != nil {
		return m.CloudCover
	}
	return nil
}

func (m *Eo) GetBands() Eo_Band {
	if m != nil {
		return m.Bands
	}
	return Eo_UNKNOWN_BAND
}

// *
// sub message request for specifying electro-optical details in stac request
type EoRequest struct {
	// epsg number of data
	Epsg int32 `protobuf:"varint,1,opt,name=epsg,proto3" json:"epsg,omitempty"`
	// only data from the platform specified
	Platform Eo_Platform `protobuf:"varint,2,opt,name=platform,proto3,enum=epl.protobuf.Eo_Platform" json:"platform,omitempty"`
	// only data from the instrument specified
	Instrument Eo_Instrument `protobuf:"varint,3,opt,name=instrument,proto3,enum=epl.protobuf.Eo_Instrument" json:"instrument,omitempty"`
	// only data from the constellation specified
	Constellation Eo_Constellation `protobuf:"varint,4,opt,name=constellation,proto3,enum=epl.protobuf.Eo_Constellation" json:"constellation,omitempty"`
	// data with a sun_azimuth equal to or in the range specified in sun_azimuth
	SunAzimuth *FloatField `protobuf:"bytes,5,opt,name=sun_azimuth,json=sunAzimuth,proto3" json:"sun_azimuth,omitempty"`
	// data with a sun_elevation equal to or in the range specified in sun_elevation
	SunElevation *FloatField `protobuf:"bytes,6,opt,name=sun_elevation,json=sunElevation,proto3" json:"sun_elevation,omitempty"`
	// data with a gsd equal to or in the range specified in gsd
	Gsd *FloatField `protobuf:"bytes,7,opt,name=gsd,proto3" json:"gsd,omitempty"`
	// data with a off_nadir equal to or in the range specified in off_nadir
	OffNadir *FloatField `protobuf:"bytes,8,opt,name=off_nadir,json=offNadir,proto3" json:"off_nadir,omitempty"`
	// data with a azimuth equal to or in the range specified in azimuth
	Azimuth *FloatField `protobuf:"bytes,9,opt,name=azimuth,proto3" json:"azimuth,omitempty"`
	// data with a cloud_cover equal to or in the range specified in cloud_cover
	CloudCover *FloatField `protobuf:"bytes,10,opt,name=cloud_cover,json=cloudCover,proto3" json:"cloud_cover,omitempty"`
	// data that possesses the bands specified in bands
	Bands                Eo_Band  `protobuf:"varint,11,opt,name=bands,proto3,enum=epl.protobuf.Eo_Band" json:"bands,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EoRequest) Reset()         { *m = EoRequest{} }
func (m *EoRequest) String() string { return proto.CompactTextString(m) }
func (*EoRequest) ProtoMessage()    {}
func (*EoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stac_088418add3b66529, []int{8}
}
func (m *EoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EoRequest.Unmarshal(m, b)
}
func (m *EoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EoRequest.Marshal(b, m, deterministic)
}
func (dst *EoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EoRequest.Merge(dst, src)
}
func (m *EoRequest) XXX_Size() int {
	return xxx_messageInfo_EoRequest.Size(m)
}
func (m *EoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EoRequest proto.InternalMessageInfo

func (m *EoRequest) GetEpsg() int32 {
	if m != nil {
		return m.Epsg
	}
	return 0
}

func (m *EoRequest) GetPlatform() Eo_Platform {
	if m != nil {
		return m.Platform
	}
	return Eo_UNKNOWN_PLATFORM
}

func (m *EoRequest) GetInstrument() Eo_Instrument {
	if m != nil {
		return m.Instrument
	}
	return Eo_UNKNOWN_INSTRUMENT
}

func (m *EoRequest) GetConstellation() Eo_Constellation {
	if m != nil {
		return m.Constellation
	}
	return Eo_UNKNOWN_CONSTELLATION
}

func (m *EoRequest) GetSunAzimuth() *FloatField {
	if m != nil {
		return m.SunAzimuth
	}
	return nil
}

func (m *EoRequest) GetSunElevation() *FloatField {
	if m != nil {
		return m.SunElevation
	}
	return nil
}

func (m *EoRequest) GetGsd() *FloatField {
	if m != nil {
		return m.Gsd
	}
	return nil
}

func (m *EoRequest) GetOffNadir() *FloatField {
	if m != nil {
		return m.OffNadir
	}
	return nil
}

func (m *EoRequest) GetAzimuth() *FloatField {
	if m != nil {
		return m.Azimuth
	}
	return nil
}

func (m *EoRequest) GetCloudCover() *FloatField {
	if m != nil {
		return m.CloudCover
	}
	return nil
}

func (m *EoRequest) GetBands() Eo_Band {
	if m != nil {
		return m.Bands
	}
	return Eo_UNKNOWN_BAND
}

func init() {
	proto.RegisterType((*StacItem)(nil), "epl.protobuf.StacItem")
	proto.RegisterMapType((map[string]*Asset)(nil), "epl.protobuf.StacItem.AssetsEntry")
	proto.RegisterType((*StacRequest)(nil), "epl.protobuf.StacRequest")
	proto.RegisterType((*BandDetails)(nil), "epl.protobuf.BandDetails")
	proto.RegisterType((*Asset)(nil), "epl.protobuf.Asset")
	proto.RegisterType((*Dtr)(nil), "epl.protobuf.Dtr")
	proto.RegisterType((*StacUpsertResponse)(nil), "epl.protobuf.StacUpsertResponse")
	proto.RegisterType((*Sar)(nil), "epl.protobuf.Sar")
	proto.RegisterType((*Eo)(nil), "epl.protobuf.Eo")
	proto.RegisterType((*EoRequest)(nil), "epl.protobuf.EoRequest")
	proto.RegisterEnum("epl.protobuf.AssetType", AssetType_name, AssetType_value)
	proto.RegisterEnum("epl.protobuf.CloudPlatform", CloudPlatform_name, CloudPlatform_value)
	proto.RegisterEnum("epl.protobuf.Sar_Platform", Sar_Platform_name, Sar_Platform_value)
	proto.RegisterEnum("epl.protobuf.Sar_Instrument", Sar_Instrument_name, Sar_Instrument_value)
	proto.RegisterEnum("epl.protobuf.Eo_Platform", Eo_Platform_name, Eo_Platform_value)
	proto.RegisterEnum("epl.protobuf.Eo_Instrument", Eo_Instrument_name, Eo_Instrument_value)
	proto.RegisterEnum("epl.protobuf.Eo_Constellation", Eo_Constellation_name, Eo_Constellation_value)
	proto.RegisterEnum("epl.protobuf.Eo_Band", Eo_Band_name, Eo_Band_value)
}

func init() { proto.RegisterFile("epl/protobuf/stac.proto", fileDescriptor_stac_088418add3b66529) }

var fileDescriptor_stac_088418add3b66529 = []byte{
	// 1849 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0xcb, 0x72, 0x1b, 0xc7,
	0xd5, 0x36, 0xee, 0xc0, 0x01, 0x41, 0xb5, 0xda, 0xb2, 0x05, 0x51, 0xfe, 0x65, 0xfe, 0x70, 0x52,
	0x51, 0xe4, 0x18, 0xa4, 0x20, 0xd1, 0xa6, 0x15, 0x27, 0xa5, 0xc1, 0x8d, 0x1c, 0x05, 0x18, 0xa0,
	0x7a, 0x40, 0xd1, 0xe5, 0xcd, 0x54, 0x73, 0xa6, 0x01, 0xc2, 0x1e, 0xcc, 0x8c, 0x67, 0x1a, 0x94,
	0x98, 0x15, 0xb7, 0x79, 0x89, 0x2c, 0x92, 0x6d, 0x5e, 0x20, 0x9b, 0xac, 0xb2, 0xcc, 0x2a, 0x8f,
	0x90, 0x27, 0x49, 0x75, 0xcf, 0x85, 0x03, 0xde, 0x4b, 0xbb, 0xac, 0xd8, 0xa7, 0xcf, 0xf7, 0xf5,
	0xe5, 0xf4, 0x77, 0x3e, 0x4c, 0x11, 0x1e, 0x32, 0xcf, 0xde, 0xf2, 0x7c, 0x97, 0xbb, 0x47, 0xcb,
	0xe9, 0x56, 0xc0, 0xa9, 0xd9, 0x94, 0x11, 0x5e, 0x63, 0x9e, 0xdd, 0x8c, 0x13, 0x1b, 0x9f, 0xcf,
	0x5c, 0x77, 0x66, 0xb3, 0x73, 0x24, 0x9f, 0x2f, 0x58, 0xc0, 0xe9, 0xc2, 0x0b, 0x31, 0x1b, 0x4f,
	0x2e, 0x02, 0xde, 0xf9, 0xd4, 0xf3, 0x98, 0x1f, 0x44, 0xf9, 0x47, 0x17, 0xf3, 0xd4, 0x39, 0x8d,
	0x52, 0x8f, 0x57, 0x8e, 0x30, 0x63, 0xee, 0x82, 0x71, 0x3f, 0x4e, 0xd6, 0x57, 0x92, 0x3f, 0x2f,
	0x59, 0x9c, 0x69, 0xfc, 0xab, 0x00, 0x65, 0x9d, 0x53, 0x53, 0xe5, 0x6c, 0x81, 0xd7, 0x21, 0x3b,
	0xb7, 0xea, 0x99, 0xcd, 0xcc, 0xd3, 0x0a, 0xc9, 0xce, 0x2d, 0xfc, 0x35, 0x94, 0xe3, 0x85, 0xea,
	0xb9, 0xcd, 0xcc, 0xd3, 0x6a, 0x6b, 0xa3, 0x99, 0xbe, 0x50, 0x73, 0x2f, 0xca, 0x76, 0x29, 0xa7,
	0x24, 0xc1, 0xe2, 0x26, 0xe4, 0x8f, 0x8e, 0xdc, 0xf7, 0xf5, 0xfc, 0x55, 0x9c, 0x9e, 0x73, 0xc2,
	0x6c, 0xd7, 0x63, 0x92, 0x23, 0x71, 0xf8, 0x25, 0x80, 0xe7, 0xbb, 0x1e, 0xf3, 0xf9, 0x9c, 0x05,
	0xf5, 0x82, 0x64, 0x3d, 0x68, 0x86, 0x77, 0x3d, 0x27, 0x2a, 0xce, 0x29, 0x49, 0xe1, 0xf0, 0x2b,
	0x28, 0xd2, 0x20, 0x60, 0x3c, 0xa8, 0x97, 0x36, 0x73, 0x4f, 0xab, 0xad, 0xc6, 0xea, 0x3e, 0xf1,
	0xad, 0x9a, 0x8a, 0x04, 0xf5, 0x1c, 0xee, 0x9f, 0x92, 0x88, 0x21, 0x6e, 0x66, 0x51, 0xce, 0x44,
	0xfd, 0xeb, 0xe5, 0xe8, 0x94, 0x17, 0xf7, 0x9b, 0xc4, 0x8f, 0x43, 0x12, 0x2c, 0x7e, 0x00, 0x05,
	0x3e, 0xe7, 0x36, 0xab, 0x57, 0x64, 0x91, 0xc2, 0x00, 0x3f, 0x01, 0x30, 0x5d, 0xdb, 0x66, 0x26,
	0x9f, 0xbb, 0x4e, 0x1d, 0x64, 0x2a, 0x35, 0x23, 0x76, 0x73, 0x8f, 0x02, 0xe6, 0x9f, 0x30, 0xab,
	0x5e, 0xbd, 0x7d, 0xb7, 0x18, 0x8b, 0x77, 0xa1, 0xe2, 0xf9, 0xae, 0xc9, 0x82, 0x80, 0x59, 0xf5,
	0xb5, 0x5b, 0x89, 0xe7, 0x60, 0xfc, 0x12, 0x4a, 0x4b, 0x4f, 0x9c, 0xda, 0xaa, 0xd7, 0x6e, 0xe5,
	0xc5, 0x50, 0xbc, 0x09, 0x59, 0xe6, 0xd6, 0xd7, 0x25, 0x01, 0x5d, 0x78, 0x35, 0x97, 0x64, 0x99,
	0x8b, 0xbf, 0x80, 0x5c, 0x40, 0xfd, 0xfa, 0x3d, 0x09, 0xb9, 0x7f, 0xa1, 0xe0, 0xd4, 0x27, 0x22,
	0x2b, 0x40, 0x16, 0xf7, 0xeb, 0xe8, 0x2a, 0x50, 0x97, 0xfb, 0x44, 0x64, 0x37, 0x34, 0xa8, 0xa6,
	0x1e, 0x06, 0x23, 0xc8, 0xfd, 0xc4, 0x4e, 0x23, 0xed, 0x89, 0x21, 0xfe, 0x35, 0x14, 0x4e, 0xa8,
	0xbd, 0x64, 0xf5, 0xac, 0x5c, 0xe7, 0xe3, 0xd5, 0x75, 0x24, 0x97, 0x84, 0x88, 0x57, 0xd9, 0xdd,
	0xcc, 0x9b, 0x7c, 0xb9, 0x88, 0x4a, 0x8d, 0x7f, 0xe6, 0xa1, 0x2a, 0x1e, 0x9e, 0xb0, 0x9f, 0x97,
	0x2c, 0xe0, 0x37, 0x2a, 0x3a, 0xfb, 0x01, 0x8a, 0xce, 0xdd, 0x51, 0xd1, 0xfb, 0x80, 0x62, 0xae,
	0xe1, 0x87, 0x67, 0x89, 0xba, 0xe1, 0xff, 0xae, 0xde, 0x2f, 0x3a, 0x30, 0xb9, 0x37, 0x5b, 0x9d,
	0xf8, 0xc0, 0xde, 0xd8, 0x4d, 0xe9, 0xbb, 0x28, 0x39, 0x9f, 0xad, 0xee, 0x9b, 0xbc, 0x7e, 0x7f,
	0xce, 0x6c, 0x2b, 0xa5, 0xf0, 0xdd, 0x94, 0x56, 0x4b, 0x77, 0x61, 0x26, 0x6a, 0x7d, 0x95, 0x56,
	0x6b, 0xf9, 0x0e, 0xd4, 0x94, 0x5e, 0xbf, 0x3e, 0xd7, 0x6b, 0xe5, 0x0e, 0xcc, 0x44, 0xb1, 0xbf,
	0x92, 0x8a, 0x05, 0x49, 0x79, 0x78, 0x49, 0xb1, 0x51, 0x4d, 0x85, 0x70, 0x1f, 0x40, 0xc1, 0x9e,
	0x2f, 0xe6, 0x5c, 0xf6, 0x5f, 0x8d, 0x84, 0x01, 0xfe, 0x14, 0x8a, 0xee, 0x74, 0x1a, 0x30, 0x2e,
	0xbb, 0x2b, 0x4f, 0xa2, 0xa8, 0xf1, 0x9f, 0x2c, 0x54, 0xdb, 0xd4, 0xb1, 0xba, 0x8c, 0xd3, 0xb9,
	0x1d, 0x60, 0x0c, 0x79, 0x87, 0x2e, 0x58, 0x24, 0x24, 0x39, 0xc6, 0x9f, 0x43, 0xd5, 0x74, 0x17,
	0x0b, 0xd7, 0x31, 0x64, 0x2a, 0x1b, 0x77, 0xbd, 0x98, 0xd2, 0x04, 0x60, 0x13, 0xaa, 0x16, 0x0b,
	0x4c, 0x7f, 0xee, 0x49, 0x5b, 0xc8, 0x49, 0x40, 0x7a, 0x0a, 0x7f, 0x05, 0xb9, 0x59, 0x60, 0x45,
	0xc2, 0x78, 0x7c, 0xe9, 0x51, 0xfb, 0xb6, 0x4b, 0xf9, 0x5b, 0xa1, 0x70, 0x22, 0x70, 0xf8, 0x1b,
	0x28, 0x53, 0xd3, 0x5c, 0xfa, 0xd4, 0x3c, 0x8d, 0x84, 0x70, 0x23, 0x27, 0x01, 0xe3, 0x7d, 0xb8,
	0x6f, 0x32, 0x87, 0x33, 0xdf, 0x78, 0x47, 0x4f, 0x98, 0xcd, 0x9c, 0x19, 0x3f, 0x8e, 0x64, 0x71,
	0xe3, 0x0a, 0x28, 0x64, 0x1d, 0x26, 0x24, 0xfc, 0x06, 0x3e, 0x9e, 0x2e, 0x6d, 0xdb, 0x78, 0x37,
	0xb7, 0xf8, 0xb1, 0x71, 0x4c, 0xed, 0xa9, 0xb1, 0xa0, 0xef, 0x23, 0xa1, 0xdc, 0xbc, 0x96, 0xe0,
	0x1d, 0x0a, 0xda, 0x3e, 0xb5, 0xa7, 0x43, 0xfa, 0xbe, 0xf1, 0xa7, 0x1c, 0x14, 0x64, 0x1b, 0x8b,
	0xf2, 0x1e, 0xfb, 0x6c, 0x1a, 0x97, 0x57, 0x8c, 0xc5, 0x1c, 0x3f, 0xf5, 0xe2, 0xba, 0xca, 0x31,
	0xde, 0x86, 0x32, 0x73, 0x8d, 0x23, 0xea, 0x58, 0x81, 0x2c, 0xe7, 0x7a, 0xeb, 0x93, 0x8b, 0x6f,
	0xde, 0x14, 0xcf, 0x46, 0x4a, 0xcc, 0x15, 0x7f, 0x85, 0xcf, 0x83, 0x74, 0x7c, 0x43, 0xae, 0x95,
	0x97, 0x9c, 0x87, 0x57, 0x38, 0xc9, 0xe4, 0xd4, 0x63, 0xa4, 0x42, 0xe3, 0x21, 0x6e, 0xc3, 0xba,
	0x69, 0xbb, 0x4b, 0xcb, 0xf0, 0x6c, 0xca, 0xa7, 0xae, 0xbf, 0x90, 0x05, 0x5f, 0x6f, 0x3d, 0x5e,
	0xe5, 0x76, 0x04, 0x66, 0x1c, 0x41, 0x48, 0xcd, 0x4c, 0x87, 0xf8, 0x97, 0xb0, 0x7e, 0xb4, 0x34,
	0x7f, 0x62, 0xdc, 0x58, 0x50, 0x87, 0xce, 0x98, 0x2f, 0x4b, 0x5e, 0x21, 0xb5, 0x70, 0x76, 0x18,
	0x4e, 0xe2, 0x2f, 0x20, 0x9a, 0x30, 0x7c, 0x36, 0x13, 0x42, 0x29, 0x49, 0xd4, 0x5a, 0x38, 0x49,
	0xe4, 0x9c, 0x10, 0x6a, 0x18, 0xcb, 0xc6, 0xaa, 0x90, 0x28, 0x12, 0x22, 0x74, 0x8f, 0x7e, 0x64,
	0x26, 0x37, 0x3c, 0xca, 0x8f, 0xa3, 0x5f, 0x25, 0x08, 0xa7, 0xc6, 0x94, 0x1f, 0x8b, 0x43, 0x44,
	0xfe, 0xc3, 0x7c, 0xc3, 0xa3, 0xa7, 0x81, 0x6c, 0x96, 0x32, 0xa9, 0x25, 0xb3, 0x63, 0x7a, 0x1a,
	0x34, 0x18, 0xe4, 0xba, 0xdc, 0xc7, 0xdb, 0x50, 0x08, 0x38, 0xf5, 0xb9, 0x7c, 0x89, 0x9b, 0x7f,
	0x34, 0x42, 0x20, 0xfe, 0x0d, 0xe4, 0x98, 0x63, 0x25, 0x5e, 0x7a, 0x3d, 0x5e, 0xc0, 0x1a, 0x53,
	0xc0, 0xc2, 0x9d, 0x0f, 0xbc, 0x80, 0xf9, 0x9c, 0xb0, 0xc0, 0x73, 0x9d, 0x80, 0x89, 0xcb, 0x05,
	0x9c, 0xf2, 0x65, 0x10, 0x09, 0x20, 0x8a, 0xc4, 0xe5, 0xc2, 0x91, 0x61, 0xba, 0x56, 0xa8, 0x84,
	0x02, 0x81, 0x70, 0xaa, 0xe3, 0x5a, 0x0c, 0x3f, 0x84, 0x92, 0x45, 0x39, 0x35, 0xe6, 0x56, 0xd4,
	0x5d, 0x45, 0x11, 0xaa, 0x56, 0xe3, 0xaf, 0x19, 0xc8, 0xe9, 0xd4, 0x17, 0x76, 0x9f, 0x3c, 0x60,
	0x46, 0x3e, 0xe0, 0xc6, 0xa5, 0xdf, 0xac, 0x66, 0xf2, 0x7e, 0x09, 0xb6, 0xf1, 0x7b, 0x28, 0x27,
	0xcf, 0xf8, 0x00, 0xd0, 0x81, 0xf6, 0x07, 0x6d, 0x74, 0xa8, 0x19, 0xe3, 0x81, 0x32, 0xe9, 0x8f,
	0xc8, 0x10, 0x7d, 0x84, 0xab, 0x50, 0xea, 0x69, 0x6f, 0x55, 0x5d, 0x99, 0xa0, 0x0c, 0xbe, 0x07,
	0x55, 0xbd, 0xa7, 0x4d, 0x54, 0xad, 0x37, 0x30, 0x9e, 0x2b, 0x28, 0xdb, 0xf8, 0x05, 0x80, 0xea,
	0x04, 0xdc, 0x5f, 0x2e, 0x98, 0x23, 0x5c, 0x06, 0xc7, 0x2b, 0xa8, 0x9a, 0x3e, 0x21, 0x07, 0xc3,
	0x9e, 0x36, 0x41, 0x1f, 0x35, 0xfe, 0x5c, 0x81, 0x6c, 0xcf, 0x15, 0x4a, 0x67, 0x5e, 0x30, 0x93,
	0x07, 0xac, 0x11, 0x39, 0xc6, 0x3b, 0xa9, 0x83, 0x67, 0xe5, 0xc1, 0x1f, 0x5d, 0x52, 0xfa, 0xe5,
	0x73, 0xe3, 0xdf, 0x02, 0xcc, 0x93, 0x7d, 0xa3, 0x16, 0x79, 0x7c, 0x89, 0x78, 0x7e, 0x34, 0x92,
	0x82, 0xe3, 0x2e, 0xd4, 0x4c, 0xd7, 0x09, 0x38, 0xb3, 0x6d, 0x2a, 0x1d, 0x2b, 0x6c, 0x97, 0x27,
	0x97, 0xf8, 0x9d, 0x34, 0x8a, 0xac, 0x92, 0xf0, 0x77, 0x50, 0x0d, 0x96, 0x8e, 0x41, 0xff, 0x38,
	0x5f, 0x2c, 0xf9, 0xf1, 0x5d, 0x7c, 0x0a, 0x82, 0xa5, 0xa3, 0x84, 0x70, 0xfc, 0x1a, 0x6a, 0x82,
	0xcd, 0x6c, 0x76, 0x12, 0x9e, 0xe1, 0x0e, 0x2e, 0xb5, 0x16, 0x2c, 0x9d, 0x5e, 0x4c, 0x88, 0x3d,
	0xb5, 0x74, 0x47, 0x4f, 0xdd, 0x85, 0x8a, 0x3b, 0x9d, 0x1a, 0x0e, 0xb5, 0xe6, 0x7e, 0xf4, 0xa3,
	0x75, 0xb3, 0xa9, 0xba, 0xd3, 0xa9, 0x26, 0xc0, 0x78, 0x07, 0x4a, 0xf1, 0x25, 0x2b, 0xb7, 0xf3,
	0x62, 0xac, 0xa8, 0x4f, 0xe8, 0x2c, 0xa6, 0x7b, 0xc2, 0xfc, 0xe8, 0xa7, 0xeb, 0xe6, 0xfa, 0x48,
	0x7c, 0x47, 0xc0, 0xf1, 0x97, 0x50, 0x08, 0xed, 0xaf, 0x7a, 0x93, 0xfd, 0x85, 0x98, 0xc6, 0xdf,
	0x33, 0xb7, 0xca, 0xb8, 0x06, 0x95, 0x81, 0xa2, 0x75, 0x75, 0x65, 0x62, 0x3c, 0x47, 0xd9, 0x74,
	0xd8, 0x42, 0xf9, 0x74, 0xf8, 0x02, 0x95, 0x85, 0xcc, 0x13, 0x70, 0xeb, 0x05, 0x5a, 0x4f, 0xe7,
	0x5f, 0x22, 0x94, 0x0e, 0x77, 0xd0, 0x26, 0x5e, 0x07, 0x48, 0xb2, 0x3b, 0x68, 0x3b, 0x9d, 0xfe,
	0x06, 0xbd, 0xc6, 0xeb, 0xe7, 0xe1, 0x2e, 0x3a, 0xcb, 0xe0, 0x35, 0x28, 0xe9, 0x87, 0x6a, 0x5f,
	0xec, 0x7c, 0x96, 0x6d, 0xfc, 0x78, 0x97, 0x0e, 0xc2, 0x25, 0xc8, 0x8d, 0x06, 0x2a, 0xca, 0xe2,
	0x32, 0xe4, 0x27, 0x2a, 0xd1, 0x51, 0x1e, 0xaf, 0x41, 0x79, 0x34, 0x50, 0x0d, 0x19, 0x15, 0x71,
	0x05, 0x0a, 0xe3, 0xd1, 0xd0, 0x78, 0x8e, 0xca, 0xb8, 0x08, 0xd9, 0xc9, 0x10, 0x21, 0xc1, 0xe9,
	0x4d, 0x86, 0x68, 0x53, 0x0c, 0x86, 0xba, 0x8e, 0x5e, 0x37, 0xde, 0x42, 0x6d, 0x45, 0xd2, 0xf8,
	0x11, 0x7c, 0x12, 0x6f, 0xd7, 0x19, 0x69, 0xfa, 0xa4, 0x37, 0x18, 0x28, 0x13, 0x75, 0xa4, 0x85,
	0x7d, 0x1f, 0x9d, 0x3a, 0xdc, 0x55, 0x53, 0xd4, 0x31, 0xca, 0x8b, 0xd1, 0x58, 0x1b, 0x29, 0xa8,
	0x2c, 0x76, 0x94, 0xd7, 0x40, 0xa8, 0xf1, 0x8f, 0x0c, 0xe4, 0xc5, 0x7b, 0x60, 0x04, 0x6b, 0xf1,
	0x7a, 0x6d, 0x45, 0xeb, 0x86, 0xcb, 0x74, 0x46, 0x8a, 0x3e, 0x51, 0x06, 0xe1, 0x32, 0xed, 0xc1,
	0x41, 0x0f, 0xe5, 0x05, 0x79, 0x8f, 0xf4, 0x7a, 0x1a, 0x2a, 0x8b, 0xd3, 0x91, 0x5e, 0x37, 0x3c,
	0x2f, 0xd9, 0x6b, 0xa3, 0xcf, 0xc4, 0x40, 0x53, 0x09, 0xda, 0x14, 0x28, 0x4d, 0x25, 0x46, 0x0b,
	0xfd, 0xbf, 0x18, 0x92, 0xbd, 0xb6, 0x4a, 0xd0, 0x77, 0x18, 0xa0, 0xa8, 0x1f, 0xaa, 0xc4, 0x78,
	0x8e, 0x5e, 0xe3, 0x6a, 0x34, 0x6e, 0x89, 0xc2, 0xde, 0x87, 0xb5, 0xb1, 0xa2, 0x75, 0xf6, 0xc9,
	0x68, 0xa8, 0x4c, 0xd4, 0x0e, 0x3a, 0xcb, 0x8a, 0x7c, 0x47, 0x25, 0xe4, 0x40, 0x47, 0x67, 0x79,
	0x11, 0x0c, 0x42, 0xe2, 0x59, 0x39, 0x09, 0x5a, 0xe8, 0x0c, 0x35, 0xfe, 0x9d, 0x87, 0x4a, 0xf2,
	0x19, 0xb5, 0xe2, 0x53, 0x85, 0xff, 0x79, 0x9f, 0xfa, 0xf6, 0x2a, 0x9f, 0xaa, 0xaf, 0xae, 0x21,
	0x9b, 0x30, 0xfc, 0xe2, 0x4c, 0x9b, 0xd4, 0xef, 0xae, 0x36, 0xa9, 0xeb, 0xc9, 0xab, 0x0e, 0xf5,
	0x2c, 0xed, 0x50, 0xd7, 0x93, 0xa4, 0x3d, 0xed, 0x5c, 0xb6, 0xa7, 0xeb, 0x19, 0xe7, 0xde, 0xd4,
	0xba, 0xe8, 0x4d, 0xd7, 0x93, 0x12, 0x63, 0xfa, 0xf6, 0x2a, 0x63, 0xba, 0xa1, 0x20, 0x1f, 0xe8,
	0x4a, 0xcf, 0xfe, 0x96, 0x81, 0x4a, 0xf2, 0xcd, 0x85, 0xef, 0x43, 0x2d, 0x6e, 0x0d, 0x45, 0xd7,
	0x7b, 0xa2, 0xa9, 0xcb, 0x90, 0x7f, 0x33, 0xee, 0xed, 0xa1, 0x8c, 0xe8, 0x92, 0xbd, 0xde, 0x68,
	0xa2, 0xf6, 0xfb, 0x61, 0x97, 0x0c, 0x7a, 0xa4, 0x83, 0x72, 0xb2, 0x71, 0x49, 0x1f, 0x09, 0xe5,
	0x96, 0x86, 0xa4, 0x6f, 0xa8, 0xdd, 0xef, 0x51, 0x21, 0x0e, 0xbe, 0x1f, 0x0e, 0x50, 0x51, 0x78,
	0x4f, 0x67, 0x64, 0xc4, 0xe4, 0x92, 0x6c, 0x22, 0xe5, 0x10, 0x95, 0x85, 0x09, 0x4d, 0xf6, 0x0f,
	0x86, 0x6d, 0x4d, 0x51, 0x07, 0xa8, 0x12, 0xfa, 0x46, 0xbf, 0x8f, 0x40, 0x24, 0xc4, 0xae, 0x46,
	0x6b, 0x7b, 0x7b, 0x1b, 0x55, 0x05, 0x41, 0xac, 0xb4, 0xf6, 0x6c, 0x1f, 0x6a, 0x2b, 0x5f, 0x79,
	0x78, 0x03, 0x3e, 0x4d, 0xcc, 0x61, 0x30, 0x3a, 0xe8, 0xa6, 0xed, 0xb4, 0x04, 0x39, 0xe5, 0x50,
	0x47, 0x19, 0x31, 0xd8, 0xeb, 0x8c, 0x51, 0x56, 0x34, 0xa8, 0xf2, 0xc3, 0x01, 0xe9, 0xa1, 0x5c,
	0x5b, 0x07, 0x64, 0xba, 0x8b, 0x95, 0xda, 0xb4, 0x2b, 0xe2, 0x73, 0x68, 0x2c, 0xa2, 0x71, 0xe6,
	0x87, 0x2f, 0x67, 0x73, 0x7e, 0xbc, 0x3c, 0x6a, 0x9a, 0xee, 0x62, 0x6b, 0xc6, 0xdc, 0xaf, 0x66,
	0xbe, 0x67, 0x6e, 0x51, 0x6f, 0xbe, 0x35, 0x73, 0x6d, 0xea, 0xcc, 0xb6, 0xd2, 0xff, 0xc4, 0xf9,
	0x4b, 0x36, 0xaf, 0x4f, 0xc6, 0xed, 0xa3, 0xa2, 0x9c, 0x78, 0xf1, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x95, 0xfa, 0x6f, 0xfe, 0x82, 0x12, 0x00, 0x00,
}
